version: v2beta1
name: django-api-template

# This is a list of `pipelines` that DevSpace can execute (you can define your own)
pipelines:
  build-dev: |-
    build_images app

  # This is the pipeline for the main command: `devspace dev` (or `devspace run-pipeline dev`)
  dev:
    run: |-
      create_deployments --all
      start_dev app

# This is a list of `images` that DevSpace can build for this project
# We recommend to skip image building during development (devspace dev) as much as possible
images:
  app:
    image: django-api-template
    dockerfile: ./Dockerfile

# This is a list of `deployments` that DevSpace can create for this project
deployments:
  app:
    kubectl:
      manifests:
        - devspace/app/

# This is a list of `dev` containers that are based on the containers created by your deployments
dev:
  app:
    labelSelector:
      component: django-api-template-web
    sync:
      - path: ./:/app
        uploadExcludeFile: .dockerignore
    # Open a terminal and use the following command to start it
    terminal:
      command: ./devspace_start.sh
    # Inject a lightweight SSH server into the container (so your IDE can connect to the remote dev env)
    ssh:
      enabled: true
    # Make the following commands from my local machine available inside the dev container
    proxyCommands:
      - command: devspace
      - command: kubectl
      - command: helm
      - gitCredentials: true
    # Forward the following ports to be able to access your application via localhost
    ports:
      - port: "8000"
    # Open the following URLs once they return an HTTP status code other than 502 or 503
    open:
      - url: http://localhost:8000
