build-mr:
  image: docker:20.10.16
  stage: build
  services:
    - docker:20.10.16-dind
  variables:
    IMAGE_TAG: $CI_PROJECT_NAME:$CI_COMMIT_REF_SLUG
  script:
    - docker build -t $IMAGE_TAG .
  except:
    - main
  when: manual

build-prod:
  image: docker:20.10.16
  stage: deploy
  services:
    - docker:20.10.16-dind
  variables:
    IMAGE_TAG: $CI_PROJECT_NAME:$CI_COMMIT_REF_SLUG
  script:
    - docker build -t $IMAGE_TAG .
    - docker save $IMAGE_TAG | gzip > $IMAGE_TAG.tar.gz
  only:
    - main
  artifacts:
    paths:
      - $IMAGE_TAG.tar.gz
